services:
  prometheus:
    image: prom/prometheus:latest
    container_name: labor_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - labor_network

  grafana:
    image: grafana/grafana:latest
    container_name: labor_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - labor_network
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: labor_node_exporter
    ports:
      - "9100:9100"
    networks:
      - labor_network

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: labor_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - labor_network

volumes:
  grafana_data:

networks:
  labor_network:
    external: true