apiVersion: apps/v1
kind: Deployment
metadata:
  name: labor-web
  namespace: labor-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: labor-web
  template:
    metadata:
      labels:
        app: labor-web
    spec:
      containers:
        - name: labor-web
          image: andshelep/labor-web:latest
          ports:
            - containerPort: 5000
          env:
            - name: APP_VERSION
              value: "v2"