apiVersion: v1
kind: Service
metadata:
  name: labor-web-service
  namespace: labor-app
spec:
  type: NodePort
  selector:
    app: labor-web
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007